baseurl = "https://blog.tritium.eu.org"
defaultContentLanguage = "zh"
languageCode = "zh-Hans"
title = "OTTB"
theme = "dream"

# [services]
# [services.disqus]
# shortname = ""
# [services.googleAnalytics]
# ID = ""

[params]
# zenMode = true

lightTheme = "emerald"
darkTheme = "forest"

# backgroundImage = "img/background.svg"
# backgroundImageDark = ""

author = "OpenTritium"
description = ""
avatar = "img/avatar.jpg"
headerTitle = "OpenTritium's Tech Blog"
# motto = ""

# footerBottomText = ""

# rss = true

# utterancesRepo = ""

# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""

# waline = true
# walineServer = ""

email = "tritium404@Hotmail.com"

siteStartYear = 2024
hasCJKLanguage = true
favicon = "./favicon.ico"

# Syntax highlighting
customSyntaxHighlighting = true
# options
# stickyNav = true
# reorderNavItems = ["search", "rss", "posts", "categories", "tags"]
# collapseNavItems = ["posts", "categories", "tags"]
# noDefaultSummaryCover = true
# showTableOfContents = true
# showSummaryCoverInPost = true
# showPrevNextPost = true
reorderShares = [ "" ]
enableSearch = true
# [params.navItems]

# [params.advanced]
# customCSS = ["css/custom.css"]
# customJS = []

# [params.experimental]
# jsDate = true
# jsDateFormat = "yyyy年MM月dd日"

[markup]
[markup.highlight]
noClasses = false